# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'hts2_art1'
    cliInstallationRepo: 'extractors'

- task: ArtifactoryMaven@2
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'hts2_art1'
    targetResolveReleaseRepo: 'maven'
    targetResolveSnapshotRepo: 'maven'
    artifactoryDeployService: 'hts2_art1'
    targetDeployReleaseRepo: 'san-maven-1'
    targetDeploySnapshotRepo: 'san-maven-1'